### ISSUE TITLE
Support for Android 4.3

### ISSUE THREAD

**Issue by alugarius** [nvllsvm/GZDoom-Android#15]
I got an old S3,
would be nice to try it at least.

**Comment by nvllsvm** [comment]
I just had to bump the minimum API level to 21 due to a change in the NDK.
https://github.com/nvllsvm/GZDoom-Android/commit/dd730c6a5634e8cdbea1ad064651583a8fc49de8

**Comment by pVVEN** [comment]
I'm sorry if this isn't the right spot to ask about this, as I'm still pretty new to GitHub, but I'm hoping you can provide some insight. I have an old Xperia Play, which at its best ran Gingerbread 2.3.3. I'd love to get some form of Doom working on it, since it has those special thumbpads that act like joysticks. 

It seems I might be able to get a copy of SlimRom running on the Play that's some version of Jellybean, and despite the reported issues of games running poorly on that version, I'd like to try to get your GZDoom port on it. Would I just need to pull down the files from the version prior to that dd730c6 commit you linked to above, drop the minimum SDK to 16, and compile the APK? Are there any other considerations I should know about?

**Comment by nvllsvm** [comment]
No clue if that will work. You may need to downgrade to an older version of the NDK to compile successfully.
